---
name: 'Srv Povio Build'

on:
  push:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Copy repository
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Installation
        run: npm install

      - name: Run tests
        run: npm run test

      - name: Run tests
        run: npm run test:e2e

      - name: Run tests
        run: npm run test:cov
